# SPDX-License-Identifier: Apache-2.0
# Copyright 2020 Intel Corporation
name: Docker image

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    env:
      DOCKER_REGISTRY: "docker.io/"
      DOCKER_REPOSITORY: "jayaramrcdac/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
  
      - run: echo GIT_SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV

      - uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          make docker-build
          make docker-push

      - name: Build and push master-latest image for Haswell CPU
        env:
          DOCKER_TAG: haswell
          CPU: haswell
        run: |
          CPU=$CPU make docker-build
          make docker-push

      - name: Build and push release Docker image for Ivybridge CPU
        env:
          DOCKER_TAG: ivybridge
          CPU: ivybridge
        run: |
          CPU=$CPU make docker-build
          make docker-push

      # Cleanup space due to runners limited storage
      - name: Cleanup Docker images
        run: docker image prune -af